eureka:
  instance:
    prefer-ip-address: true

spring:  
  cloud:
    loadbalancer:
      retry:
        enabled: false

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false

endpoints:
  enabled: false
  bus:
    enabled: true
  refresh:
    enabled: true
  loggers:
    enabled: true
  env:
    enabled: true